canonical/launchpad-manual

- explanation/charms.rst
We've switched to new (qa)staging databases that are entirely controlled by developers.  The procedure still needs some tidying up, but this should work for now.
> charms: Update (qa)staging DB user management process

- .readthedocs.yaml
It suddenly fails when PDFs are being built - as we do not need PDFs and the error is not really obvious, let's skip PDF building for now.
> Fix build on Read the Docs

- .custom_wordlist.txt
- reference/css.rst
- reference/index.rst
This adds a short CSS style guide that is based on the BEM principles, as discussed at the stand-up.
I also asked Peter from the Web Engineering team and confirmed that Vanilla framework also generally uses these principles. I added a few examples from the Vanilla framework as well.
> Add a short CSS style guide

- .custom_wordlist.txt
- how-to/running.rst
This allows connecting to containers using their domain name instead of their IP address.
> Add a note about setting up DNS to use LXD's DNS

- readme.rst
Simple introductory  paragraph with a title change
> Update readme introduction and title

- how-to/index.rst
- how-to/transfer-project-ownership.rst
This is particularly relevant for private projects and projects with private content since it requires more than just updating the 'maintainer' field
> Add new page with notes on how to transfer project ownership

- explanation/performance.rst
The link to a page that explains Big O Notation  (https://towardsdatascience.com/understanding-time-complexity-with-python-examples-2bda6e8158a7) often fails link checks with a 429 error.
This commit replaces that link with a wikipedia page of the same topic.
> Replace link that often fails link checks in performance.rst

- how-to/create-bot-account.rst
- how-to/index.rst
Adding a very short set of notes about how to add a bot account.
I am still not 100% sure whether this should simply go into the `manage-users` page, but I thought maybe a new page made sense. Let me know what your thoughts are on that.
> Add page about how to create a bot account

- custom_conf.py
- how-to/triage-bugs.rst
It fixes the 'FixBugs' link in `triage-bugs.rst`.
> Fix 'FixBugs'

- custom_conf.py
- explanation/javascript-unittesting.rst
It fixes the 'JavaScriptIntegrationTesting' link in `javascript-unittesting.rst`.
> Fix 'JavaScriptIntegrationTesting' link

- custom_conf.py
- explanation/launchpad-ppa.rst
It fixes the 'Getting' link in `launchpad-ppa.rst`.
> Fix 'Getting'

- custom_conf.py
- explanation/mail.rst
It fixes the 'Help' link in `explanation/mail.rst`.
> Fix 'Help' link

- custom_conf.py
- explanation/javascript-integration-testing.rst
It fixes the 'JavascriptUnitTesting' link in `explanation/javascript-integration-testing.rst`.
> Fix 'JavascriptUnitTesting' link

- how-to/common-development-tasks.rst
- how-to/getting-started.rst
- how-to/index.rst
- how-to/launchpad-development-tips.rst
- how-to/operating-launchpad.rst
This addresses #37 by reorganizing how-to folders and their toctrees. This issue was assigned in canonical/open-documentation-academy#76.
> Change folder structure and toctrees to put how-to subsections in the left nav.

- custom_conf.py
- explanation/launchpad-ppa.rst
- explanation/working-with-db-devel.rst
It fixes the 'Running' link in `explanation/working-with-db-devel.rst` and `explanation/launchpad-ppa.rst`.
> Fix 'Running' link

- custom_conf.py
- explanation/css.rst
It fixes the 'UI/CssSprites' link in `explanation/css.rst`.
> Fix 'UI/CssSprites' link

- custom_conf.py
- explanation/code.rst
It fixes the 'Loggerhead' link in `explanation/code.rst`
> Fix 'Loggerhead' link

- .custom_wordlist.txt
- .sphinx/spellingcheck.yaml
- explanation/javascript-buildsystem.rst
As per the issue raised in the Open Documentation Academy (Issue https://github.com/canonical/open-documentation-academy/issues/77), the page "The Launchpad JavaScript Build System" was removed from the exclusion list and `make spelling` was run to include it in the spell checker.
Some comments with regards to the changes:
* `WSGI`: the capitalised version is acceptable as per [their documentation](https://wsgi.readthedocs.io/en/latest/what.html) and was already included in the file `.custom_wordlist.txt`
* mailing list discussion URL link: changed it to a hyperlink following the same process in other pages. Tested the redirect using `make run` and it opens up the URL correctly
Thanks
> Correct spelling errors (The Launchpad JavaScript Build System page)

- .sphinx/spellingcheck.yaml
- explanation/mail.rst
As per the issue raised in the Open Documentation Academy (Issue canonical/open-documentation-academy#77), the page "Launchpad Mail" was removed from the exclusion list and `make spelling` was run to include it in the spell checker.
The only change that was made, was updating how the URLs are displayed. Its incorrect formatting made the spellchecker pick up `barry` as an incorrect spelled word.
The command `make run` was executed to ensure the changes resulted in the URLs being displayed correctly:
Thanks
> Spelling checks (Launchpad Mail page)

- .custom_wordlist.txt
- .sphinx/spellingcheck.yaml
- explanation/navigation-menus.rst
- explanation/url-traversal.rst
As per the issue raised in the Open Documentation Academy (Issue https://github.com/canonical/open-documentation-academy/issues/77), the page "URL Traversal" and "Navigation Menus" were removed from the exclusion list and `make spelling` was run to include it in the spell checker.
I accidentally did not create a branch for the "Navigation Menus" page changes which resulted in this pull request having changes for two pages.
Changes include adding words to the exclusion list, spelling corrections where American English was used as well as changes to the formatting for displaying inline code
Thanks
> Spell check (URL traversal + Navigation Menus)

- .custom_wordlist.txt
- .sphinx/spellingcheck.yaml
- explanation/security-policy.rst
As per the issue raised in the Open Documentation Academy (Issue https://github.com/canonical/open-documentation-academy/issues/77), the page "Security Policy" was removed from the exclusion list and `make spelling` was run to include it in the spell checker.
All qualifying words were added to the exclusion list and words such as `adapters` and `un-proxied` were corrected in the relevant .rst file.
Thanks
> Spelling checks (Security policy page)

- .custom_wordlist.txt
- .sphinx/spellingcheck.yaml
- explanation/database-performance.rst
As per the issue raised in the Open Documentation Academy (Issue canonical/open-documentation-academy#77), the page "Database Performance" was removed from the exclusion list and `make spelling` was run to include it in the spell checker.
All qualifying words were added to the exclusion list and words such as `extermis` was corrected in the relevant .rst file.
Thanks
> Check Spelling (Database Performance page)

- .custom_wordlist.txt
- .sphinx/spellingcheck.yaml
- explanation/storm-migration-guide.rst
As per the issue raised in the Open Documentation Academy (Issue https://github.com/canonical/open-documentation-academy/issues/77), the page "Database Performance" was removed from the exclusion list and `make spelling` was run to include it in the spell checker.
Some comments with regards to the changes:
* A lot of inline code was incorrectly formatted which resulted in the code snippets popping up as spelling errors. The formatting was corrected which removed them from being checked by the spell checker
* The "Questions" section's formatting was inconsistent and was standardized throughout the section
I am also not quite convinced on the formatting of the section "Tips on Converting Tests", but left it as is, as I assume it will be addressed when there is a comprehensive review of the …
> Check Spelling errors (Storm migration guide)

- how-to/running.rst
* doc: update running launchpad how-to with pynacl fix for arm64
> Add fix for pynacl to "Setting up and running Launchpad"

- reference/services/fetch-service.rst
The build fails due to a reference to a Google doc in edit mode (even though it didn't in my earlier PR.)
> Fix the link checker

- custom_conf.py
- explanation/code.rst
This PR refers to https://github.com/canonical/open-documentation-academy/issues/78#event-13157268254
It fixes the broken 'Soyuz' link in `code.rst`.
> add 'Soyuz' link

- .custom_wordlist.txt
- custom_conf.py
- explanation/code.rst
- explanation/concepts.rst
- explanation/index.rst
It adds the missing `concepts.rst` and fixes the broken link in `code.rst`. 
Running `make linkcheck` throws the following error: 
```
$HOME/launchpad-manual/explanation/concepts.rst: WARNING: document isn't included in any toctree
```
Let me know if there's anything I need to do to resolve the error.
> add concepts.rst, fix broken link in code.rst

- how-to/index.rst
- how-to/launchpad-development-tips.rst
Group `codehosting-locally` and `rename-database-table` into `how-to/launchpad-development-tips` section.
> Group howto pages into dev tips

- .custom_wordlist.txt
- how-to/debugging.rst
Fixing the format of `debugging.rst` page
> fix format how-to/debugging page

- .custom_wordlist.txt
- explanation/security.rst
- explanation/storm-migration-guide.rst
- reference/python.rst
- tutorials/creating-a-rock-build-using-apis.rst
4 links were broken because of outside factors. One of them because the rockcraft team changed the name of a page slightly. And the rest of them because the old web-page for Storm ORM was discontinued. Fixed them with their new versions.
And 2 additions to the custom word list for the spell-checking
> A small fix to the broken links

- developer/how-to/running.rst
This PR removes a stray space in the shebang line of the LXD profile script.
> Fix a typo in the shebang of the LXD profile shell script

- custom_conf.py
The link checker is no usable for gnu.org and fsf.org, as they rate limit access, and so the link checker will take several hours, instead of minutes.
Ignoring both URLs for now.
> Exclude rate limited links

- release-notes.rst
This PR adds a note about the removal of bzr codebrowse links on Launchpad pages.
> Add a release note about removing bzr codebrowse links

- release-notes.rst
This PR mentions the fact that we have now decommissioned the bzr codebrowse service (loggerhead) on launchpad.net
> Mention the bzr codebrowse service decommissioning in the release notes

- developer/how-to/database-schema-changes-process.rst
We are not using todrop schemas now. We drop tables using `DROP TABLE` since there is no slony now.
> Update database schema changes process

- docs/developer/reference/services/fetch-service.rst
Mention that the button has moved from Administer recipe to Edit recipe for
snaps and has two modes for the fetch service policy.
Add that the fetch service option is also available for charms.
> Update fetch service page to mention changes about 'Use Fetch Service' button

- docs/index.rst
Worked on the launchpad manual and add an anchor link to the word Ubuntu, so when users click on it , it will take them to to Ubuntu landing page.
> Added link to the word Ubuntu on the Homepage

- docs/developer/tutorials/creating-a-page-in-launchpad.rst
This PR hyperlinked the 'ZCML directive' as requested in this issue: https://github.com/canonical/open-documentation-academy/issues/268
> hyperlinked the zcml directive phrase

- docs/user/reference/teams/mailing-lists.rst
Fixed mail-archive link that wasn't being ignored because of missing forward slash.
> chore: Fixed mail-archive link that wasn't being ignored.

- docs/user/how-to/using-openid.rst
The broken link to Pbwiki has recently been failing linkchecks. Additionally, the reference may be outdated since Pbwiki was renamed to Pbworks and has a different operating model. The link itself is not critical to the documentation because it was included as one of several examples of sites that support OpenID.
> chore: Deleting broken link to Pbwiki.
