.custom_wordlist.txt, reference/python.rst
... as it was removed some time ago.
=> Remove mentioning of SQLObject

custom_conf.py
With this fix our community will be able to report issues directly from the documentation.
=> Udpate GitHub repo for issue creation

reference/services/build-farm.rst
=> Uppercase Internet

.custom_wordlist.txt, how-to/debug-tests-with-visual-studio-code.rst, how-to/index.rst
Explanation on how to configure your environment to start debugging tests interactively with visual studio code integration
=> Documentation for debugging tests with vscode integration

custom_conf.py, explanation/branches.rst
It fixes the first link tagged as `needs update` in the `linkcheck_ignore` list. It's the first of many, so let me know if it was implemented correctly and I'll proceed down the list. 
Note that I commented out rather than remove the link from `custom_conf.py` to avoid conflict if/when submitting multiple PRs.
=> Fix 'PolicyAndProcess/DatabaseSchemaChangesProcess'

how-to/develop-with-buildd.rst
Updated old information to interact with builder locally.
Added documentation to interact with XML-RPC and our builder on our staging environments.
Added proxy configuration with XML-RPC.
=> Add XML-RPC interaction with staging builders

.custom_wordlist.txt, .sphinx/spellingcheck.yaml, custom_conf.py, how-to/operating-launchpad.rst, how-to/porting-builders-to-newer-ubuntu-versions.rst
WIP. Docs around porting builders to newer Ubuntu versions.
=> Add documentation around how to port builders to a target ubuntu version

how-to/manage-users.rst
Suggestion instead of https://github.com/canonical/launchpad-manual/pull/116
=> Fix steps to anoint team members

reference/services/fetch-service.rst
Add references to the log folder configured for rsync.
=> Update fetch-service logs

.custom_wordlist.txt, custom_conf.py, reference/index.rst, reference/services/code-import.rst
This is only a minimal start and needs to be improved over time.
=> Add service description for code import

reference/services/fetch-service.rst
Added proper documentation for inspectors configuration and the certificate installation.
=> fetch-service: added inspectors and certificates docs

.custom_wordlist.txt, .wordlist.txt, custom_conf.py, explanation/engineering-overview-translations.rst, how-to/porting-builders-to-newer-ubuntu-versions.rst, tutorials/creating-a-rock-build-using-apis.rst, tutorials/index.rst
In this tutorial we are creating a Rock build using the APIs.
=> Tutorial to create Rock builds.

how-to/operating-launchpad.rst, how-to/use-lp-shell.rst
Added a simple documentation to show how to set-up and use lp-shell.
=> Add simple lp-shell documentation

explanation/performance.rst
Remove reference to broken link.
=> Remove reference to a broken Google Drive link

index.rst, release-notes.rst
Add release note for disabling building i386 by default Add release note for new merge proposal event webooks
=> Add Release Notes section

tutorials/creating-a-rock-build-using-apis.rst
=> Fix grammar error

includes/important_bazaar_deprecation.rst, user/how-to/work-with-bazaar/using-launchpad-with-bazaar.rst
As requested by ticket https://github.com/canonical/open-documentation-academy/issues/240
=> Announce bazaar deprecation

user/explanation/answers/answer-tracker.rst, user/explanation/answers/index.rst, user/explanation/index.rst
Fixes https://github.com/canonical/open-documentation-academy/issues/233
If something needs to be improved, please do not hesitate to let me know :D!
=> Adding index file and populating toctree

user/explanation/collaborating-using-launchpad.rst, user/explanation/your-launchpad-account.rst
Fixes https://github.com/canonical/open-documentation-academy/issues/239
Replaced internal links with references and added a document label in order to reference it.
If something needs to be improved, please do not hesitate to let me know!! :D
=> Fixing broken links and adding labels

user/explanation/index.rst, user/explanation/translating-with-launchpad/index.rst, user/explanation/translating-with-launchpad/translating-with-launchpad.rst
Fixes https://github.com/canonical/open-documentation-academy/issues/234
If something needs to be changed, please let me know! Thanks! :100:
=> Adding index file to translations page

user/explanation/privacy-confidentiality-and-disclosure.rst, user/explanation/what-is-launchpad.rst
Fix https://github.com/canonical/open-documentation-academy/issues/238
If something needs to be improved, please let me know :D
=> Fixing broken links

user/how-to/import-ssh-keys.rst
=> fix: use git instead of launchpad

.custom_wordlist.txt, contribute-to-our-docs.rst
Added a section for the Canonical Open Documentation Academy in the contributing section.
=> feat: Added a section for the documentation academy 

user/explanation/index.rst, user/explanation/working-with-code/code-imports.rst, user/explanation/working-with-code/index.rst
Fixes https://github.com/canonical/open-documentation-academy/issues/236
=> Adding index to working-with-code

docs/conf.py, docs/user/how-to/work-with-code-hosted-on-launchpad/git-hosting-on-launchpad.rst
Fixing a broken internal link to launchpad API docs
=> chore: Fixing broken link to lp api docs.

docs/developer/reference/services/buildbot.rst
We moved to using git from bzr
=> Update buildbot.rst 

docs/developer/explanation/charms.rst
Updated four links to Juju docs that were migrated. Previous links were failing linkcheck CI.
=> edit: Updated failing links to Juju documentation.
